rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - windows
  semi:
    - 2
    - always
env:
  browser: true
globals:
    angular: false
extends: 'eslint:recommended'
plugins:
    - angular
